name: run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 12.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Run tests
        run: yarn test
